# Ejemplo de despliegue en Kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laplace-api
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      containers:
        - name: api
          image: tu-registry/laplace-api:prod
          envFrom:
            - secretRef:
                name: laplace-secrets
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
