# Ejemplo de autoescalado para Ollama
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ollama-scaler
spec:
  scaleTargetRef:
    name: ollama
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "60"
