version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/laplace
      - REDIS_URL=redis://redis:6379/0
      - RABBITMQ_URL=amqp://admin:securepass123@rabbitmq:5672
      - WEAVIATE_URL=http://weaviate:8080
    depends_on:
      - db
      - redis
      - rabbitmq
      - weaviate
    networks:
      - laplace-network

  worker:
    build: ./worker
    volumes:
      - ./worker:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/laplace
      - RABBITMQ_URL=amqp://admin:securepass123@rabbitmq:5672
      - WEAVIATE_URL=http://weaviate:8080
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
      weaviate:
        condition: service_started
    networks:
      - laplace-network
    restart: on-failure

  bert-service:
    build: ./bert-service
    ports:
      - "5000:5000"
    volumes:
      - ./bert-service:/app
    environment:
      - MODEL_PATH=/app/models
    networks:
      - laplace-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./api/migrations:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=laplace
    ports:
      - "5432:5432"
    networks:
      - laplace-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - laplace-network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=securepass123
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - laplace-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  weaviate:
    image: semitechnologies/weaviate:1.19.6
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "text2vec-transformers"
      ENABLE_MODULES: "text2vec-transformers"
      TRANSFORMERS_INFERENCE_API: "http://bert-service:5000"
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - laplace-network

networks:
  laplace-network:
    driver: bridge

volumes:
  postgres_data:
  weaviate_data:
  rabbitmq_data:
  redis_data: